{{ if .Values.pipelinerunner.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "pipelinerunner.name" . }}
rules:
  - apiGroups:
      - jenkins.io
    resources:
      - pipelineactivities
    verbs:
      - create
      - list
      - update
      - get
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - list
    - watch
{{ end }}    