# Default values for prow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deck:
  replicaCount: 2
  probe:
    path: /
  image:
    repository: jenkinsxio/deck
    tag: pipeline14
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  args:
    - --hook-url=http://hook/plugin-help
    - --tide-url=http://tide
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8080
    annotations:
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx\nnginx.ingress.kubernetes.io/auth-type: basic\nnginx.ingress.kubernetes.io/auth-secret: jx-basic-auth"

echotest:
  interval: 10m
  command: /bin/date

pipelinerunner:
  enabled: false
  image:
    repository: jenkinsxio/builder-maven
    tag: 0.1.255
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 180
  probe:
    livenessPath: /health
    readinessPath: /ready
  command:
  - jx
  args:
  - "controller"
  - "pipelinerunner"
  resources:
    limits:
     cpu: 400m
     memory: 256Mi
    requests:
     cpu: 200m
     memory: 128Mi
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8080
  env:
    GIT_AUTHOR_NAME: "jenkins-x-bot"
    GIT_AUTHOR_EMAIL: "jenkins-x@googlegroups.com"
    XDG_CONFIG_HOME: "/home/jenkins"
    MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

buildnum:
  enabled: true
  image:
    repository: jenkinsxio/jx
    jxTag: 1.3.941
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 180
  probe:
    livenessPath: /health
    readinessPath: /ready
  command:
  - jx
  args:
  - "controller"
  - "buildnumbers"
  resources:
    limits:
     cpu: 400m
     memory: 256Mi
    requests:
     cpu: 200m
     memory: 128Mi
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8080

crier:
  image:
    repository: jenkinsxio/crier
    tag: pipeline14
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 180
  args:
    - -gerrit-workers=0
    - -github-workers=1
    - -logtostderr
    - -config-path=/etc/config/config.yaml
    - -github-token-path=/etc/github/oauth
  resources:
    limits:
     cpu: 400m
     memory: 256Mi
    requests:
     cpu: 200m
     memory: 128Mi

branchprotector:
  enabled: false
  schedule: "54 * * * *"  # Every hour at 54 minutes past the hour
  image:
    repository: gcr.io/k8s-prow/branchprotector
    tag: v20181113-9b11013
  imagePullPolicy: IfNotPresent
  args:
    - --config-path=/etc/config/config.yaml
    - --github-token-path=/etc/github/oauth
    - --confirm
    - --github-endpoint=https://api.github.com
  resources:
    limits:
     cpu: 400m
     memory: 256Mi
    requests:
     cpu: 200m
     memory: 128Mi

hook:
  replicaCount: 2
  probe:
    path: /
  image:
    repository: jenkinsxio/hook
    tag: pipeline14
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 180
  args:
    - --dry-run=false
  resources:
    limits:
     cpu: 400m
     memory: 256Mi
    requests:
     cpu: 200m
     memory: 128Mi
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8888
    annotations:
      fabric8.io/expose: "true"

horologium:
  replicaCount: 1
  image:
    repository: jenkinsxio/horologium
    tag: pipeline14
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  args:
    - --dry-run=false
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi

plank:
  image:
    repository: jenkinsxio/plank
    tag: pipeline14
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  args:
    - --dry-run=false
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi

build:
  image:
    repository: jenkinsxio/build
    tag: pipeline14
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi

pipeline:
  image:
    repository: jenkinsxio/pipeline
    tag: pipeline14
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi

sinker:
  replicaCount: 1
  image:
    repository: jenkinsxio/sinker
    tag: pipeline14
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi

plugins:
  yaml: ""

user: james-foo


tide:
  replicaCount: 1
  probe:
    path: /
  image:
    repository: jenkinsxio/tide
    tag: pipeline14
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 30
  args:
    - --dry-run=false
    #- --github-endpoint=http://ghproxy
    - --github-endpoint=https://api.github.com
  resources:
    limits:
     cpu: 200m
     memory: 256Mi
    requests:
     cpu: 100m
     memory: 128Mi
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8888
    annotations:
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx\nnginx.ingress.kubernetes.io/auth-type: basic\nnginx.ingress.kubernetes.io/auth-secret: jx-basic-auth"